-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.access_logs
(
    log_id bigserial NOT NULL,
    user_id integer,
    target_patient_id integer,
    action character varying(255) COLLATE pg_catalog."default",
    "timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    ip_address inet,
    user_agent text COLLATE pg_catalog."default",
    resource_affected character varying(100) COLLATE pg_catalog."default",
    severity character varying(20) COLLATE pg_catalog."default" DEFAULT 'INFO'::character varying,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'SUCCESS'::character varying,
    CONSTRAINT access_logs_pkey PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS public.alert_notifications
(
    alert_id serial NOT NULL,
    event_id integer,
    user_id integer,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'Sent'::character varying,
    message text COLLATE pg_catalog."default",
    sent_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    severity character varying(20) COLLATE pg_catalog."default" DEFAULT 'INFO'::character varying,
    CONSTRAINT alert_notifications_pkey PRIMARY KEY (alert_id)
);

CREATE TABLE IF NOT EXISTS public.announcements
(
    id serial NOT NULL,
    title character varying(100) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    is_active boolean DEFAULT true,
    created_by integer,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT announcements_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.anomaly_events
(
    event_id serial NOT NULL,
    patient_id integer,
    reading_id bigint,
    anomaly_type character varying(50) COLLATE pg_catalog."default",
    ocsvm_score numeric(10, 4),
    detected_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT anomaly_events_pkey PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS public.device_whitelist
(
    serial_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    device_name character varying(50) COLLATE pg_catalog."default",
    firmware_version character varying(20) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'ACTIVE'::character varying,
    added_by integer,
    created_at timestamp with time zone DEFAULT now(),
    last_heartbeat timestamp with time zone,
    assigned_patient_id integer,
    last_serviced_at timestamp with time zone DEFAULT now(),
    CONSTRAINT device_whitelist_pkey PRIMARY KEY (serial_number)
);

CREATE TABLE IF NOT EXISTS public.facilities
(
    facility_id serial NOT NULL,
    facility_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT facilities_pkey PRIMARY KEY (facility_id)
);

CREATE TABLE IF NOT EXISTS public.ip_blacklist
(
    id serial NOT NULL,
    ip_address character varying(45) COLLATE pg_catalog."default" NOT NULL,
    reason text COLLATE pg_catalog."default",
    banned_by integer,
    banned_at timestamp with time zone DEFAULT now(),
    CONSTRAINT ip_blacklist_pkey PRIMARY KEY (id),
    CONSTRAINT ip_blacklist_ip_address_key UNIQUE (ip_address)
);

CREATE TABLE IF NOT EXISTS public.legal_documents
(
    doc_id serial NOT NULL,
    doc_type character varying(50) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    version character varying(20) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean DEFAULT false,
    created_by integer,
    published_at timestamp with time zone DEFAULT now(),
    CONSTRAINT legal_documents_pkey PRIMARY KEY (doc_id)
);

CREATE TABLE IF NOT EXISTS public.patient_access
(
    access_id serial NOT NULL,
    user_id integer,
    patient_id integer,
    relationship character varying(50) COLLATE pg_catalog."default",
    access_level character varying(20) COLLATE pg_catalog."default" DEFAULT 'View'::character varying,
    assigned_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT patient_access_pkey PRIMARY KEY (access_id)
);

CREATE TABLE IF NOT EXISTS public.patients
(
    patient_id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    birthdate date NOT NULL,
    patient_type character varying(50) COLLATE pg_catalog."default",
    device_serial_number character varying(50) COLLATE pg_catalog."default",
    baseline_data jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_archived boolean DEFAULT false,
    facility_id integer,
    CONSTRAINT patients_pkey PRIMARY KEY (patient_id),
    CONSTRAINT patients_device_mac_address_key UNIQUE (device_serial_number)
);

CREATE TABLE IF NOT EXISTS public.profiles_caregivers
(
    profile_id serial NOT NULL,
    user_id integer,
    caregiver_type character varying(50) COLLATE pg_catalog."default",
    certifications text[] COLLATE pg_catalog."default",
    years_experience integer,
    agency_name character varying(150) COLLATE pg_catalog."default",
    emergency_contact character varying(50) COLLATE pg_catalog."default",
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    work_shift character varying(50) COLLATE pg_catalog."default",
    notification_preferences text[] COLLATE pg_catalog."default",
    CONSTRAINT profiles_caregivers_pkey PRIMARY KEY (profile_id),
    CONSTRAINT profiles_caregivers_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.profiles_medical_staff
(
    profile_id serial NOT NULL,
    user_id integer,
    license_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    specialization character varying(100) COLLATE pg_catalog."default",
    hospital_affiliation character varying(150) COLLATE pg_catalog."default",
    years_of_practice integer,
    schedule_availability jsonb,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    practice_type character varying(50) COLLATE pg_catalog."default",
    is_solo_practitioner boolean DEFAULT false,
    CONSTRAINT profiles_medical_staff_pkey PRIMARY KEY (profile_id),
    CONSTRAINT profiles_medical_staff_license_number_key UNIQUE (license_number),
    CONSTRAINT profiles_medical_staff_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.reports
(
    report_id serial NOT NULL,
    user_id integer,
    patient_id integer,
    report_type character varying(50) COLLATE pg_catalog."default",
    file_url character varying(255) COLLATE pg_catalog."default",
    generated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reports_pkey PRIMARY KEY (report_id)
);

CREATE TABLE IF NOT EXISTS public.role_permissions
(
    id serial NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    module_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    is_enabled boolean NOT NULL DEFAULT true,
    updated_by integer,
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT role_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT role_permissions_role_module_id_key UNIQUE (role, module_id)
);

CREATE TABLE IF NOT EXISTS public.sensor_readings
(
    reading_id bigserial NOT NULL,
    patient_id integer,
    heart_rate integer,
    spo2 integer,
    temperature numeric(5, 2),
    moisture_value integer,
    recorded_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT sensor_readings_pkey PRIMARY KEY (reading_id)
);

CREATE TABLE IF NOT EXISTS public.session_revocations
(
    user_id integer NOT NULL,
    revoked_before timestamp with time zone NOT NULL DEFAULT now(),
    revoked_by integer,
    reason text COLLATE pg_catalog."default",
    CONSTRAINT session_revocations_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.system_configs
(
    config_key character varying(50) COLLATE pg_catalog."default" NOT NULL,
    config_value jsonb NOT NULL,
    description text COLLATE pg_catalog."default",
    updated_by integer,
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT system_configs_pkey PRIMARY KEY (config_key)
);

CREATE TABLE IF NOT EXISTS public.user_documents
(
    document_id serial NOT NULL,
    user_id integer,
    document_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    file_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    upload_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    verification_status character varying(20) COLLATE pg_catalog."default" DEFAULT 'Pending'::character varying,
    reviewed_by integer,
    rejection_reason text COLLATE pg_catalog."default",
    CONSTRAINT user_documents_pkey PRIMARY KEY (document_id)
);

CREATE TABLE IF NOT EXISTS public.user_permission_overrides
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    module_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    is_granted boolean NOT NULL,
    override_reason text COLLATE pg_catalog."default",
    overridden_by integer,
    overridden_at timestamp with time zone DEFAULT now(),
    CONSTRAINT user_permission_overrides_pkey PRIMARY KEY (id),
    CONSTRAINT user_permission_overrides_user_id_module_id_key UNIQUE (user_id, module_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default",
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default",
    last_name character varying(50) COLLATE pg_catalog."default",
    role character varying(20) COLLATE pg_catalog."default" NOT NULL,
    is_biometric_enabled boolean DEFAULT false,
    is_mfa_enabled boolean DEFAULT false,
    mfa_secret character varying(255) COLLATE pg_catalog."default",
    mfa_method character varying(20) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_verified boolean DEFAULT false,
    account_status character varying(20) COLLATE pg_catalog."default" DEFAULT 'Pending_Review'::character varying,
    mobile_number character varying(20) COLLATE pg_catalog."default",
    middle_initial character varying(5) COLLATE pg_catalog."default",
    is_locked boolean DEFAULT false,
    failed_login_attempts integer DEFAULT 0,
    force_logout_at timestamp with time zone,
    facility_id integer,
    last_activity_at timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS public.access_logs
    ADD CONSTRAINT access_logs_target_patient_id_fkey FOREIGN KEY (target_patient_id)
    REFERENCES public.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.access_logs
    ADD CONSTRAINT access_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.alert_notifications
    ADD CONSTRAINT alert_notifications_event_id_fkey FOREIGN KEY (event_id)
    REFERENCES public.anomaly_events (event_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.alert_notifications
    ADD CONSTRAINT alert_notifications_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.announcements
    ADD CONSTRAINT announcements_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.anomaly_events
    ADD CONSTRAINT anomaly_events_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES public.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.anomaly_events
    ADD CONSTRAINT anomaly_events_reading_id_fkey FOREIGN KEY (reading_id)
    REFERENCES public.sensor_readings (reading_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.device_whitelist
    ADD CONSTRAINT device_whitelist_added_by_fkey FOREIGN KEY (added_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.device_whitelist
    ADD CONSTRAINT device_whitelist_assigned_patient_id_fkey FOREIGN KEY (assigned_patient_id)
    REFERENCES public.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_device_patient
    ON public.device_whitelist(assigned_patient_id);


ALTER TABLE IF EXISTS public.ip_blacklist
    ADD CONSTRAINT ip_blacklist_banned_by_fkey FOREIGN KEY (banned_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.legal_documents
    ADD CONSTRAINT legal_documents_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.patient_access
    ADD CONSTRAINT patient_access_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES public.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.patient_access
    ADD CONSTRAINT patient_access_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.patients
    ADD CONSTRAINT patients_facility_id_fkey FOREIGN KEY (facility_id)
    REFERENCES public.facilities (facility_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.profiles_caregivers
    ADD CONSTRAINT profiles_caregivers_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS profiles_caregivers_user_id_key
    ON public.profiles_caregivers(user_id);


ALTER TABLE IF EXISTS public.profiles_medical_staff
    ADD CONSTRAINT profiles_medical_staff_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS profiles_medical_staff_user_id_key
    ON public.profiles_medical_staff(user_id);


ALTER TABLE IF EXISTS public.reports
    ADD CONSTRAINT reports_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES public.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reports
    ADD CONSTRAINT reports_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT role_permissions_updated_by_fkey FOREIGN KEY (updated_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sensor_readings
    ADD CONSTRAINT sensor_readings_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES public.patients (patient_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.session_revocations
    ADD CONSTRAINT session_revocations_revoked_by_fkey FOREIGN KEY (revoked_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.session_revocations
    ADD CONSTRAINT session_revocations_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS session_revocations_pkey
    ON public.session_revocations(user_id);


ALTER TABLE IF EXISTS public.system_configs
    ADD CONSTRAINT system_configs_updated_by_fkey FOREIGN KEY (updated_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_documents
    ADD CONSTRAINT user_documents_reviewed_by_fkey FOREIGN KEY (reviewed_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_documents
    ADD CONSTRAINT user_documents_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_permission_overrides
    ADD CONSTRAINT user_permission_overrides_overridden_by_fkey FOREIGN KEY (overridden_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_permission_overrides
    ADD CONSTRAINT user_permission_overrides_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_facility_id_fkey FOREIGN KEY (facility_id)
    REFERENCES public.facilities (facility_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;