import { User, Patient, VitalSign, Alert, Event } from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'caregiver@alaga.com',
    role: 'caregiver',
    name: 'Maria Santos',
  },
  {
    id: '2',
    email: 'medstaff@alaga.com',
    role: 'medical_staff',
    name: 'Dr. Jose Reyes',
  },
];

export const mockPatients: Patient[] = [
  {
    id: 'p0',
    name: 'Patient A',
    age: 45,
    medicalConditions: ['Hypertension'],
    baselineVitals: { heartRate: 72, temperature: 36.9, spo2: 97 },
    caregiverId: '1',
    deviceId: 'ESP32-000',
    hrDeviceId: 'HR-SENSOR-000',
    diaperDeviceId: 'DIAPER-000',
    deviceBattery: 78,
    hrDeviceBattery: 85,
    diaperDeviceBattery: 90,
    deviceConnected: true,
    hrDeviceConnected: true,
    diaperDeviceConnected: true,
    roomNumber: 'A101',
    illness: 'Hypertension management',
    emergencyContact: { name: 'Juan Santos', relationship: 'Son', phone: '+63 912 345 6789' },
    lastUpdated: new Date(),
  },
  {
    id: 'p1',
    name: 'Baby Miguel',
    age: 1,
    medicalConditions: ['Nocturnal Enuresis'],
    baselineVitals: { heartRate: 120, temperature: 37.0, spo2: 98 },
    caregiverId: '1',
    deviceId: 'ESP32-001',
    hrDeviceId: 'HR-SENSOR-001',
    diaperDeviceId: 'DIAPER-001',
    deviceBattery: 85,
    hrDeviceBattery: 88,
    diaperDeviceBattery: 82,
    deviceConnected: true,
    hrDeviceConnected: true,
    diaperDeviceConnected: true,
    roomNumber: 'B205',
    illness: 'Nocturnal Enuresis monitoring',
    emergencyContact: { name: 'Rosa Miguel', relationship: 'Mother', phone: '+63 917 234 5678' },
    lastUpdated: new Date(),
  },
  {
    id: 'p2',
    name: 'Lola Carmen',
    age: 78,
    medicalConditions: ['Diabetes', 'Hypertension', 'Incontinence'],
    baselineVitals: { heartRate: 75, temperature: 36.8, spo2: 96 },
    caregiverId: '1',
    deviceId: 'ESP32-002',
    hrDeviceId: 'HR-SENSOR-002',
    diaperDeviceId: 'DIAPER-002',
    deviceBattery: 92,
    hrDeviceBattery: 95,
    diaperDeviceBattery: 88,
    deviceConnected: true,
    hrDeviceConnected: true,
    diaperDeviceConnected: true,
    roomNumber: 'C312',
    illness: 'Diabetes Type 2, Incontinence',
    emergencyContact: { name: 'Pedro Carmen', relationship: 'Husband', phone: '+63 918 345 6789' },
    lastUpdated: new Date(),
  },
  {
    id: 'p3',
    name: 'Lolo Pedro',
    age: 82,
    medicalConditions: ['COPD'],
    baselineVitals: { heartRate: 68, temperature: 36.7, spo2: 94 },
    // [CHANGE] Reassigned to '1' so he appears on your dashboard for the demo
    caregiverId: '1',
    deviceId: 'ESP32-003',
    hrDeviceId: 'HR-SENSOR-003',
    diaperDeviceId: 'DIAPER-003',
    deviceBattery: 15,
    hrDeviceBattery: 12,
    diaperDeviceBattery: 18,
    deviceConnected: false, // Critical Alert: Offline
    hrDeviceConnected: false,
    diaperDeviceConnected: false,
    roomNumber: 'D101',
    illness: 'COPD - Respiratory monitoring',
    emergencyContact: { name: 'Ana Pedro', relationship: 'Daughter', phone: '+63 919 456 7890' },
    lastUpdated: new Date(Date.now() - 300000),
  },
  {
    id: 'p4',
    name: 'Mrs. Elena Cruz',
    age: 65,
    medicalConditions: ['Post-Stroke'],
    baselineVitals: { heartRate: 78, temperature: 36.9, spo2: 95 },
    caregiverId: '1',
    deviceId: 'ESP32-004',
    hrDeviceId: 'HR-SENSOR-004',
    diaperDeviceId: 'DIAPER-004',
    deviceBattery: 88,
    hrDeviceBattery: 91,
    diaperDeviceBattery: 85,
    deviceConnected: true,
    hrDeviceConnected: true,
    diaperDeviceConnected: true,
    roomNumber: 'A203',
    illness: 'Post-stroke rehabilitation',
    emergencyContact: { name: 'Carlos Cruz', relationship: 'Husband', phone: '+63 920 567 8901' },
    lastUpdated: new Date(),
  },
  {
    id: 'p5',
    name: 'Baby Sofia',
    age: 0.5,
    medicalConditions: ['Premature Birth'],
    baselineVitals: { heartRate: 135, temperature: 37.1, spo2: 97 },
    caregiverId: '1',
    deviceId: 'ESP32-005',
    hrDeviceId: 'HR-SENSOR-005',
    diaperDeviceId: 'DIAPER-005',
    deviceBattery: 95,
    hrDeviceBattery: 93,
    diaperDeviceBattery: 87,
    deviceConnected: true,
    hrDeviceConnected: true,
    diaperDeviceConnected: true,
    roomNumber: 'B102',
    illness: 'Premature Birth Monitoring',
    emergencyContact: { name: 'Luisa Sofia', relationship: 'Mother', phone: '+63 921 678 9012' },
    lastUpdated: new Date(),
  },
  {
    id: 'p6',
    name: 'Mr. Roberto Tan',
    age: 70,
    medicalConditions: ['Heart Failure', 'Diabetes'],
    baselineVitals: { heartRate: 82, temperature: 36.6, spo2: 93 },
    // [CHANGE] Reassigned to '1'
    caregiverId: '1',
    deviceId: 'ESP32-006',
    hrDeviceId: 'HR-SENSOR-006',
    diaperDeviceId: 'DIAPER-006',
    deviceBattery: 72,
    hrDeviceBattery: 75,
    diaperDeviceBattery: 80,
    deviceConnected: true,
    hrDeviceConnected: true,
    diaperDeviceConnected: true,
    roomNumber: 'C204',
    illness: 'Congestive Heart Failure',
    emergencyContact: { name: 'Maria Tan', relationship: 'Wife', phone: '+63 922 789 0123' },
    lastUpdated: new Date(),
  },
  {
    id: 'p7',
    name: 'Baby Lucas',
    age: 2,
    medicalConditions: ['Nocturnal Enuresis'],
    baselineVitals: { heartRate: 110, temperature: 36.8, spo2: 96 },
    caregiverId: '1',
    deviceId: 'ESP32-007',
    hrDeviceId: 'HR-SENSOR-007',
    diaperDeviceId: 'DIAPER-007',
    deviceBattery: 81,
    hrDeviceBattery: 84,
    diaperDeviceBattery: 83,
    deviceConnected: true,
    hrDeviceConnected: true,
    diaperDeviceConnected: true,
    roomNumber: 'B206',
    illness: 'Nocturnal Enuresis',
    emergencyContact: { name: 'Ana Lucas', relationship: 'Mother', phone: '+63 923 890 1234' },
    lastUpdated: new Date(),
  },
  {
    id: 'p8',
    name: 'Mrs. Gloria Ramos',
    age: 75,
    medicalConditions: ['Alzheimer\'s'],
    baselineVitals: { heartRate: 70, temperature: 36.7, spo2: 95 },
    caregiverId: '2', // Kept one for '2' just in case
    deviceId: 'ESP32-008',
    hrDeviceId: 'HR-SENSOR-008',
    diaperDeviceId: 'DIAPER-008',
    deviceBattery: 68,
    hrDeviceBattery: 70,
    diaperDeviceBattery: 86,
    deviceConnected: true,
    hrDeviceConnected: true,
    diaperDeviceConnected: true,
    roomNumber: 'D202',
    illness: 'Alzheimer\'s Disease',
    emergencyContact: { name: 'Juan Ramos', relationship: 'Son', phone: '+63 924 901 2345' },
    lastUpdated: new Date(),
  },
];

// Generate mock vital signs for the last 24 hours
export const generateMockVitalSigns = (patientId: string, baseline: Patient['baselineVitals']): VitalSign[] => {
  const vitals: VitalSign[] = [];
  const now = Date.now();

  for (let i = 0; i < 288; i++) { // Every 5 minutes for 24 hours
    const timestamp = new Date(now - i * 5 * 60 * 1000);
    vitals.push({
      id: `v${patientId}-${i}`,
      patientId,
      timestamp,
      heartRate: baseline.heartRate + Math.random() * 10 - 5,
      temperature: baseline.temperature + Math.random() * 0.4 - 0.2,
      spo2: baseline.spo2 + Math.random() * 2 - 1,
      moistureLevel: Math.random() * 20,
    });
  }

  return vitals.reverse();
};

export const mockAlerts: Alert[] = [
  {
    id: 'a1',
    patientId: 'p1',
    type: 'bedwetting',
    severity: 'warning',
    title: 'Bed-wetting Detected',
    message: 'Moisture sensors detected a bed-wetting event for Baby Miguel.',
    timestamp: new Date(Date.now() - 600000),
    acknowledged: false,
  },
  {
    id: 'a2',
    patientId: 'p2',
    type: 'vital_signs',
    severity: 'critical',
    title: 'Abnormal Heart Rate',
    message: 'Heart rate of 105 bpm exceeds normal threshold for Lola Carmen.',
    timestamp: new Date(Date.now() - 900000),
    acknowledged: false,
  },
  {
    id: 'a3',
    patientId: 'p3',
    type: 'device',
    severity: 'critical',
    title: 'Low Battery',
    message: 'Device battery is at 15% for Lolo Pedro. Please charge soon.',
    timestamp: new Date(Date.now() - 1200000),
    acknowledged: false,
  },
  {
    id: 'a4',
    patientId: 'p3', // Lolo Pedro (Now assigned to You)
    type: 'device',
    severity: 'critical',
    title: 'Device Disconnected',
    message: 'Lost connection to monitoring device for Lolo Pedro.',
    timestamp: new Date(Date.now() - 300000),
    acknowledged: false,
  },
  {
    id: 'a5',
    patientId: 'p1',
    type: 'anomaly',
    severity: 'warning',
    title: 'Abnormal Pattern Detected',
    message: 'One-Class SVM detected an unusual bed-wetting pattern (Confidence: 87%).',
    timestamp: new Date(Date.now() - 7200000),
    acknowledged: true,
    acknowledgedBy: '1',
    acknowledgedAt: new Date(Date.now() - 7100000),
  },
];

export const mockEvents: Event[] = [
  // Keeping events as is for history
  {
    id: 'e1',
    patientId: 'p1',
    type: 'bedwetting',
    timestamp: new Date(Date.now() - 600000),
    data: { moistureLevel: 85, duration: 120 },
  },
];